services:
  tusd:
    image: tusproject/tusd:latest
    container_name: tusd_server
    ports:
      - "8084:8084"
    volumes:
      - "./tusd-data:/tusd-data"
    entrypoint: ["tusd"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "-host=0.0.0.0"
      - "-port=8084"
      - "-hooks-http=http://host.docker.internal:3007/tus-hooks"
      - "-hooks-http-forward-headers=Authorization"
      - "-base-path=/sosialhjelp/upload/files"
      - "-hooks-enabled-events=pre-create,post-create,post-finish"
      - "-upload-dir=/tusd-data"
      - "-behind-proxy"

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    ports:
      - "3010:3000"
    volumes:
      - "/tmp:/dockerVolume"

  postgres:
    image: postgres:latest
    container_name: postgres-upload
    restart: always
    environment:
      POSTGRES_DB: sosialhjelp-upload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
