ktor:
  application:
    modules:
      - no.nav.sosialhjelp.ApplicationKt.module
  deployment:
    port: 3007
jwt:
  audience: "$IDPORTEN_CLIENT_ID:default"
  issuer: "$IDPORTEN_ISSUER:http://localhost:8888/default"
database:
  user: postgres
  password: postgres
  host: localhost
  port: 54322
  name: sosialhjelp-upload
thumbnailer:
  outputDir: "./tusd-data"