runtimeEnv: ${RUNTIME_ENV:local}
ktor:
  application:
    modules:
      - no.nav.sosialhjelp.upload.ApplicationKt.module
  deployment:
    port: 3007
jwt:
  audience: "$IDPORTEN_CLIENT_ID:default"
  issuer: "$IDPORTEN_ISSUER:http://localhost:8888/default"
  jwks_uri: "$IDPORTEN_JWKS_URI:http://localhost:8888/default/jwks"
database:
  user: "$POSTGRES_USERNAME:postgres"
  password: "$POSTGRES_PASSWORD:postgres"
  jdbcUrl: "$POSTGRES_JDBC_URL:jdbc:postgresql://localhost:54322/sosialhjelp-upload"
gotenberg:
  url: "$GOTENBERG_URL:http://localhost:3010/forms/libreoffice/convert"
storage:
  basePath: "../digisos-docker-compose/tusd-data"
  bucketName: "$BUCKET_NAME:sosialhjelp-upload-dev"
  gcsCredentials: "$GCS_CREDENTIALS:"
fiks:
  baseUrl: "$FIKS_URL:http://localhost:8989/sosialhjelp/mock-alt-api/fiks"
  integrasjonsid: "$INTEGRASJONSID_FIKS:id"
  integrasjonspassord: "$INTEGRASJONPASSORD_FIKS:passord"
virus:
  scanner:
    url: "$CLAMAV_URL:"
texas:
  url: "$NAIS_TOKEN_ENDPOINT:http://localhost:8081/api/v1/token"
