apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      external:
        - host: unleash.nais.io
        - host: digisos.ekstern.dev.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
        - host: test.idporten.no
      rules:
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-soknad-api-mock
        - application: sosialhjelp-idporten-mock
        - application: sosialhjelp-texas-mock
    inbound:
      rules:
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-innsyn-mock
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - secret: sosialhjelp-innsyn-api-unleash-api-token
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "mock-alt,log-console,mock-redis"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks"
    - name: FIKS_DOKUMENTLAGER_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks/dokumentlager"
    - name: FIKS_SVAR_UT_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks/svarut"
    - name: INNSYN_LOGINURL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt/login"
    - name: NORG_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/norg_endpoint_url"
    - name: PDL_AUDIENCE
      value: "dev-gcp:teamdigisos:sosialhjelp-mock-alt-api-mock"
    - name: PDL_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/pdl_endpoint_url"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-innsyn-api"
    - name: UNLEASH_ENV
      value: "mock"
    - name: VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER
      value: "Socio;10.1.16,mock-alt;1.0-MOCKVERSJON,Testsystemet;1.0.0"
    - name: SOKNAD_API_URL
      value: "http://sosialhjelp-soknad-api-mock/sosialhjelp/soknad-api"
    - name: FIKS_KLAGE_ENDPOINT_URL
      value: http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/klage
    - name: IDPORTEN_ISSUER
      value: https://sosiauth2.ekstern.dev.nav.no/default
    - name: IDPORTEN_CLIENT_ID
      value: default
    - name: NAIS_TOKEN_ENDPOINT
      value: http://sosialhjelp-texas-mock/api/v1/token
    - name: NAIS_TOKEN_EXCHANGE_ENDPOINT
      value: http://sosialhjelp-texas-mock/api/v1/token/exchange
