name: "Restart all environments"
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy_dev:
    uses: ./.github/workflows/deploy-dev.yml
    with:
      config-file-name: dev
    secrets: inherit
  deploy_mock:
    uses: ./.github/workflows/deploy-dev.yml
    with:
      config-file-name: mock
    secrets: inherit
  deploy_prod:
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit
